name: my_project_app
description: A new Flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  quoter: ^0.0.1
  get:
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.5.2
  google_fonts: ^2.1.0
  charts_flutter: ^0.12.0
  fl_chart: ^0.60.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Hip_Thrust.png
    - img/